// Rich starter menu used when provisioning a new café, so its storefront looks
// fully stocked out of the box. The owner edits/removes from here.

export const STARTER_CATEGORIES = [
  { key: "ice-blended", label: "Ice Blended", sort: 1 },
  { key: "hot-coffee", label: "Hot Coffee", sort: 2 },
  { key: "tea", label: "Tea", sort: 3 },
  { key: "food", label: "Food", sort: 4 },
];

// k = item key (unique within tenant), catKey = category key
export const STARTER_ITEMS = [
  { k: "signature-ice-blended", name: "Signature Ice Blended", catKey: "ice-blended", price: 385, img: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=700", desc: "Our house blended coffee — creamy coffee, milk and ice, finished with a swirl.", veg: true, kcal: 320, caffeine: 95, protein: 6, sugar: 38, signature: true, rating: 4.8, reviews: 210, origin: "100% Arabica, medium roast.", ingredients: ["Espresso", "Whole milk", "Ice", "Cane sugar"], allergens: ["Milk"], tags: ["cold", "sweet", "signature", "treat"], sizes: [{ name: "Small", price: 345 }, { name: "Regular", price: 385 }, { name: "Large", price: 425 }], aiTip: "Ask for it 'lite' to cut ~30% sugar." },
  { k: "mocha-ice-blended", name: "Mocha Ice Blended", catKey: "ice-blended", price: 410, img: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=700", desc: "Chocolate meets coffee, blended smooth and topped with whipped cream.", veg: true, kcal: 380, caffeine: 105, protein: 7, sugar: 44, rating: 4.7, reviews: 130, origin: "Arabica with single-origin cocoa.", ingredients: ["Espresso", "Milk", "Chocolate", "Whipped cream", "Ice"], allergens: ["Milk", "Soy"], tags: ["cold", "sweet", "treat"], sizes: [{ name: "Regular", price: 410 }, { name: "Large", price: 450 }], aiTip: "The most indulgent pick." },
  { k: "vanilla-ice-blended", name: "Vanilla Ice Blended", catKey: "ice-blended", price: 375, img: "https://images.unsplash.com/photo-1599639668273-01692b3b7c39?w=700", desc: "Madagascar vanilla blended with milk & ice — creamy and caffeine-free.", veg: true, kcal: 340, caffeine: 0, protein: 6, sugar: 40, rating: 4.6, reviews: 90, origin: "Madagascar bourbon vanilla.", ingredients: ["Vanilla", "Milk", "Ice", "Cane sugar"], allergens: ["Milk"], tags: ["cold", "sweet", "treat", "decaf", "low-caffeine"], sizes: [{ name: "Regular", price: 375 }], aiTip: "Caffeine-free — good for evenings." },
  { k: "matcha-ice-blended", name: "Matcha Ice Blended", catKey: "ice-blended", price: 410, img: "https://images.unsplash.com/photo-1568649929103-28ffbefaca1e?w=700", desc: "Ceremonial-grade matcha blended cold — earthy and gently sweet.", veg: true, kcal: 340, caffeine: 40, protein: 5, sugar: 30, rating: 4.7, reviews: 75, origin: "Matcha from Uji, Kyoto.", ingredients: ["Matcha", "Milk", "Ice", "Cane sugar"], allergens: ["Milk"], tags: ["cold", "refreshing", "low-caffeine"], sizes: [{ name: "Regular", price: 410 }], aiTip: "Lower caffeine, steady energy." },
  { k: "cafe-latte", name: "Café Latte", catKey: "hot-coffee", price: 295, img: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=700", desc: "Double espresso with steamed milk and a layer of microfoam.", veg: true, kcal: 190, caffeine: 150, protein: 9, sugar: 14, rating: 4.8, reviews: 320, origin: "House espresso blend.", ingredients: ["Double espresso", "Steamed milk"], allergens: ["Milk"], tags: ["hot", "high-protein"], sizes: [{ name: "Regular", price: 295 }, { name: "Large", price: 335 }], aiTip: "9g protein — your most filling hot coffee." },
  { k: "cappuccino", name: "Cappuccino", catKey: "hot-coffee", price: 275, img: "https://images.unsplash.com/photo-1534778101976-62847782c213?w=700", desc: "Espresso, steamed milk and airy foam, dusted with cocoa.", veg: true, kcal: 150, caffeine: 150, protein: 8, sugar: 10, rating: 4.7, reviews: 240, origin: "House espresso blend.", ingredients: ["Double espresso", "Steamed milk", "Foam"], allergens: ["Milk"], tags: ["hot", "high-protein"], sizes: [{ name: "Regular", price: 275 }], aiTip: "Balanced and under 150 kcal." },
  { k: "flat-white", name: "Flat White", catKey: "hot-coffee", price: 305, img: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=700", desc: "Velvety steamed milk over a double ristretto. Smooth and strong.", veg: true, kcal: 170, caffeine: 160, protein: 8, sugar: 11, rating: 4.7, reviews: 150, origin: "House espresso blend.", ingredients: ["Double ristretto", "Steamed milk"], allergens: ["Milk"], tags: ["hot", "high-protein"], sizes: [{ name: "Regular", price: 305 }], aiTip: "Stronger coffee flavour than a latte." },
  { k: "americano", name: "Americano", catKey: "hot-coffee", price: 245, img: "https://images.unsplash.com/photo-1551030173-122aabc4489c?w=700", desc: "Double espresso lengthened with hot water. Bold, black, zero sugar.", veg: true, kcal: 10, caffeine: 150, protein: 1, sugar: 0, rating: 4.6, reviews: 120, origin: "House espresso blend.", ingredients: ["Double espresso", "Hot water"], allergens: [], tags: ["hot", "low-cal", "vegan"], sizes: [{ name: "Regular", price: 245 }], aiTip: "10 kcal and vegan — the lightest coffee." },
  { k: "iced-black-tea", name: "Iced Black Tea", catKey: "tea", price: 220, img: "https://images.unsplash.com/photo-1499638673689-79a0b5115d87?w=700", desc: "Single-estate Assam black tea over ice.", veg: true, kcal: 5, caffeine: 25, protein: 0, sugar: 0, rating: 4.5, reviews: 60, origin: "Single-estate Assam.", ingredients: ["Black tea", "Water", "Ice"], allergens: [], tags: ["cold", "refreshing", "low-cal", "low-caffeine", "vegan"], sizes: [{ name: "Regular", price: 220 }], aiTip: "5 kcal, vegan, most refreshing." },
  { k: "masala-chai", name: "Masala Chai Latte", catKey: "tea", price: 260, img: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=700", desc: "Spiced tea simmered with steamed milk, cardamom and ginger.", veg: true, kcal: 180, caffeine: 40, protein: 6, sugar: 22, rating: 4.7, reviews: 110, origin: "Assam CTC + house masala.", ingredients: ["Black tea", "Milk", "Cardamom", "Ginger"], allergens: ["Milk"], tags: ["hot", "sweet", "low-caffeine"], sizes: [{ name: "Regular", price: 260 }], aiTip: "Comforting and lower caffeine." },
  { k: "green-tea", name: "Jasmine Green Tea", catKey: "tea", price: 210, img: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=700", desc: "Delicate green tea scented with jasmine. Light and calming.", veg: true, kcal: 0, caffeine: 30, protein: 0, sugar: 0, rating: 4.5, reviews: 50, origin: "Jasmine green, Fujian style.", ingredients: ["Green tea", "Jasmine", "Hot water"], allergens: [], tags: ["hot", "low-cal", "low-caffeine", "vegan"], sizes: [{ name: "Regular", price: 210 }], aiTip: "Zero calories, antioxidant-rich." },
  { k: "butter-croissant", name: "Butter Croissant", catKey: "food", price: 180, img: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=700", desc: "Flaky, all-butter croissant baked fresh each morning.", veg: true, kcal: 290, caffeine: 0, protein: 6, sugar: 6, rating: 4.6, reviews: 80, origin: "Baked in-house daily.", ingredients: ["Wheat flour", "Butter", "Milk"], allergens: ["Gluten", "Milk"], tags: ["food", "treat"], sizes: [{ name: "One", price: 180 }], aiTip: "Classic pairing for any drink." },
  { k: "almond-croissant", name: "Almond Croissant", catKey: "food", price: 220, img: "https://images.unsplash.com/photo-1620921568790-c1cf8984624c?w=700", desc: "Butter croissant with almond cream and toasted flakes.", veg: true, kcal: 410, caffeine: 0, protein: 9, sugar: 18, rating: 4.5, reviews: 40, origin: "Filled in-house.", ingredients: ["Wheat flour", "Butter", "Almond cream", "Egg"], allergens: ["Gluten", "Milk", "Egg", "Nuts"], tags: ["food", "treat", "high-protein"], sizes: [{ name: "One", price: 220 }], aiTip: "9g protein and filling." },
  { k: "veg-sandwich", name: "Grilled Veg & Pesto Sandwich", catKey: "food", price: 320, img: "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=700", desc: "Grilled vegetables, basil pesto and melted cheese on sourdough.", veg: true, kcal: 430, caffeine: 0, protein: 16, sugar: 6, rating: 4.4, reviews: 35, origin: "Made fresh to order.", ingredients: ["Sourdough", "Vegetables", "Pesto", "Mozzarella"], allergens: ["Gluten", "Milk", "Nuts"], tags: ["food", "high-protein"], sizes: [{ name: "One", price: 320 }], aiTip: "16g protein — the most filling." },
  { k: "blueberry-muffin", name: "Blueberry Muffin", catKey: "food", price: 190, img: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=700", desc: "Soft muffin studded with real blueberries and a sugar top.", veg: true, kcal: 360, caffeine: 0, protein: 5, sugar: 28, rating: 4.3, reviews: 30, origin: "Baked in-house daily.", ingredients: ["Wheat flour", "Blueberries", "Butter", "Egg"], allergens: ["Gluten", "Milk", "Egg"], tags: ["food", "sweet", "treat"], sizes: [{ name: "One", price: 190 }], aiTip: "A sweet grab-and-go bite." },
];
